### ISSUE TITLE
O3653-8 Exercise 3 - Lab ODataException on UserOperations.GetUsersAsyn

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#139]
When testing the Project only the blue Screen appears - but no Output is created - stable bug.

**Comment by jthake** [comment]
Originally created in email. Details of error are

Getting an ODataException (below) when opening the Lab Files project located in \O3653\O3653-8 Deep Dive into the Office 365 Unified API\Lab Files. This is using Windows Phone 8.1 and Windows 8 project template. Issue #143 will replace this exercise but needs fixing in mean time. 

Microsoft.OData.Core.ODataException
 
The entity instance value of type 'Microsoft.Graph.User' doesn't have a value for property 'objectId'. To compute an entity's metadata, its key and concurrency-token property values must be provided.
 
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetPrimitivePropertyClrValue(ODataEntry entry, String propertyName, String entityTypeName, Boolean isKeyProperty)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.<get_KeyProperties>b__d(IEdmStructuralProperty p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.get_KeyProperties()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.get_ComputedKeyProperties()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeId()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeAndCacheId()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeEditLink()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetEditLink()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetReadLink()
   at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetStreamReadLink(String streamPropertyName)
   at Microsoft.OData.Core.ODataStreamReferenceValue.get_ReadLink()
   at Microsoft.OData.Client.Materialization.MaterializerEntry.UpdateEntityDescriptor()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.ReadEntryCore()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.<LazyReadEntries>d__0.MoveNext()
   at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
   at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
   at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
   at Microsoft.OData.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.OData.ProxyExtensions.PagedCollection`2..ctor(DataServiceContextWrapper context, QueryOperationResponse`1 qor)
   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<>c__DisplayClass2f`2.<ExecuteAsync>b__2d(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__31`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at O365_Win_Profile.UserOperations.<GetUsersAsync>d__0.MoveNext()

**Comment by jthake** [comment]
@Senajs I need more information than what you’ve replied with to replicate this.

**Comment by Senajs** [comment]
This was a Feedback of a Student - he followed closely the steps in the lab and ran into this issue.. what would Help here?

**Comment by jthake** [comment]
What version of Visual Studio 2013/2015 and office tools are they using?

**Comment by Senajs** [comment]
Visual Studio 2013 Professional or Community Edition all with at least Update 4 or 5. Office developer Tools Update August 2015. Visual Studio 2015 without Update 1 and with the Office Tools BEFORE the November update

**Comment by jthake** [comment]
From one of the reporters:
MS Office 365 API Tools Version: 1.4.50723.1
Visual Studio 2013 Update 4

**Comment by FHeemskerk** [comment]
Hi,
Senaj asked me to provide some extra info, so:

The problem is on the UserOperations.GetUsersAsync:

Microsoft.OData.Core.ODataException
The entity instance value of type 'Microsoft.Graph.User' doesn't have a value for property 'objectId'. To compute an entity's metadata, its key and concurrency-token property values must be provided.

I haven't done anything to troubleshoot, as this isn't something i need right now, but just a lab that doesn't seem to work. Offcourse, i could be doing something wrong, but i was just following the lab descriptions.

VS2013 info:
Microsoft Visual Studio Premium 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.00081
Installed Version: Premium

LightSwitch for Visual Studio 2013   06191-004-0454001-02982
Microsoft LightSwitch for Visual Studio 2013
Team Explorer for Visual Studio 2013   06191-004-0454001-02982
Microsoft Team Explorer for Visual Studio 2013
Visual Basic 2013   06191-004-0454001-02982
Microsoft Visual Basic 2013
Visual C# 2013   06191-004-0454001-02982
Microsoft Visual C# 2013
Visual C++ 2013   06191-004-0454001-02982
Microsoft Visual C++ 2013
Visual F# 2013   06191-004-0454001-02982
Microsoft Visual F# 2013
Visual Studio 2013 Code Analysis Spell Checker   06191-004-0454001-02982
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker
Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.
The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.
Windows Phone SDK 8.0 - ENU   06191-004-0454001-02982
Windows Phone SDK 8.0 - ENU
Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio
ASP.NET and Web Tools   12.5.60612.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure
ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
ASP.NET Web Frameworks and Tools 2013   5.2.30612.0
For additional information, visit http://www.asp.net/
Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Microsoft Advertising SDK for Windows Phone   
Microsoft Advertising SDK for Windows Phone
Build 
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools
NuGet Package Manager   2.8.60610.756
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
Office Developer Tools for Visual Studio 2013 ENU   12.0.40814
Microsoft Office Developer Tools for Visual Studio 2013 ENU
PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
ResXManager   1.0.0.58
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.
SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools
Windows Installer XML Toolset   3.9.1208.0
Windows Installer XML Toolset version 3.9.1208.0
Copyright (c) Outercurve Foundation. All rights reserved.
Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.
Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by jthake** [comment]
We are currently in progress of replacing the SDK usage in the labs to use ADAL libraries and directly call the REST API. More information to follow on this.
