### ISSUE TITLE
O3653-8 Exercise 3 - Microsoft.OData.Core.ODataException

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#140]
says "the Entity instance value of type "Microsoft.graph.user" doesnt have a value for property "objectID". To compute an entity's metadata, its key and concurrency-token property values must be provided..

**Comment by jthake** [comment]
Originally created in email. Details of error are

Getting an ODataException (below) when opening the Lab Files project located in \O3653\O3653-8 Deep Dive into the Office 365 Unified API\Lab Files. This is using Windows Phone 8.1 and Windows 8 project template. Issue #143 will replace this exercise but needs fixing in mean time.

Microsoft.OData.Core.ODataException

The entity instance value of type 'Microsoft.Graph.User' doesn't have a value for property 'objectId'. To compute an entity's metadata, its key and concurrency-token property values must be provided.

at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetPrimitivePropertyClrValue(ODataEntry entry, String propertyName, String entityTypeName, Boolean isKeyProperty)
at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.b__d(IEdmStructuralProperty p)
at System.Linq.Enumerable.WhereSelectListIterator2.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.ODataEntryMetadataContextWithModel.get_KeyProperties()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.get_ComputedKeyProperties()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeId()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeAndCacheId()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.ComputeEditLink()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetEditLink()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetReadLink()
at Microsoft.OData.Core.Evaluation.ODataConventionalEntityMetadataBuilder.GetStreamReadLink(String streamPropertyName)
at Microsoft.OData.Core.ODataStreamReferenceValue.get_ReadLink()
at Microsoft.OData.Client.Materialization.MaterializerEntry.UpdateEntityDescriptor()
at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.ReadEntryCore()
at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadEntry(MaterializerEntry& entry)
at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.d__0.MoveNext()
at Microsoft.OData.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
at Microsoft.OData.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
at Microsoft.OData.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
at Microsoft.OData.Client.MaterializeAtom.MoveNextInternal()
at Microsoft.OData.Client.MaterializeAtom.MoveNext()
at System.Linq.Enumerable.d__11.MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at Microsoft.OData.ProxyExtensions.PagedCollection2..ctor(DataServiceContextWrapper context, QueryOperationResponse1 qor)
at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<>c__DisplayClass2f2.<ExecuteAsync>b__2d(IAsyncResult r) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.OData.ProxyExtensions.DataServiceContextWrapper.<ExecuteAsync>d__312.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at O365_Win_Profile.UserOperations.d__0.MoveNext()
