### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by akt2006** [OfficeDev/TrainingContent#497]
module.js:549
    throw err;
    ^

Error: Cannot find module '@microsoft/sp-build-web'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\SharePointFrameworkWebpart\TrainingContent-master\TrainingContent-master\SharePoint\SharePointFramework\07 Working with different JavaScript frameworks and libraries\Demos\Exercise 3\helloworld-webpart-jquery\gulpfile.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
PS D:\SharePointFrameworkWebpart\TrainingContent-master\TrainingContent-master\SharePoint\SharePointFramework\07 Working with different JavaScript frameworks and libraries\Demos\Exercise 3\helloworld-webpart-jquery>

**Comment by andrewconnell** [comment]
The module you reference has been retired. Suggest you try again with the new module and if you have an issue, post it in that repo: https://github.com/OfficeDev/TrainingContent/tree/master/SharePoint/SharePointFramework

#please-close
